# Generated by Django 5.0.1 on 2024-02-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authormodel',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
